### ISSUE TITLE
Create requirements.txt

### ISSUE THREAD

**Issue by sjortiz** [RomeroPaola/PyShop#1]
# Rationale
As we know it's standard practice to include a `requirements.txt` file in each python project. To keep up with the good standards/practices, we should add the file to the repo.

# References
https://pip.readthedocs.io/en/1.1/requirements.html

**Comment by RomeroPaola** [comment]
asgiref==3.2.7
Django==3.0.4
pytz==2019.3
sqlparse==0.3.1
