### ISSUE TITLE
Follow the python style guide

### ISSUE THREAD

**Issue by sjortiz** [RomeroPaola/PyShop#3]
# Rationale
It's good to use an standard code style (or styling rules in general) in our applications, python provide us with the `pep-8` where they define the ideal style a python project should follow.

Maybe you don't have the time to read and digest the document in one sit, TLDR; it's a long read.
The good news is that there are tools that validate this standard and tell you specifically where and which fixes need to be applied such as:
- pep8 (a python tool with the same name, this tool has been renamed to pycodestyle, so you might as well just install the newer version)
- pylint
- flake8

I recommend you install pep8 for now, as its the less rigorous with the style (the others check for extra rules not included on the pep-8).

You can get this tool by typing `pip install pep8` and execute it as `pep8 .`

# References
- https://www.python.org/dev/peps/pep-0008/

**Comment by RomeroPaola** [comment]
Done!
