### ISSUE TITLE
Remove the virtual env from the repo

### ISSUE THREAD

**Issue by sjortiz** [RomeroPaola/PyShop#4]
# Rationale
The virtual environment is supposed to be used only in your local machine, I could be using a totally different setup, or a setup with fixes only required in my machine due to external configuration (Such as my default python version), or I will much rather prefer to not use it at all.

Also any binary that can be recreated from code doesn't need to part of the repo because the code is already there.

You could simply remove this from the repository or further advance the repo structure by adding a .`gitignore` as well

# References
- https://git-scm.com/docs/gitignore
- https://github.com/github/gitignore/blob/master/Python.gitignore
- https://stackoverflow.com/questions/6590688/is-it-bad-to-have-my-virtualenv-directory-inside-my-git-repository

**Comment by sjortiz** [comment]
I realized I forgot to mention but remove all the `__pycache__` folders as well, before creating the `.gitignore` those shouldn't be added to the repo either.

If you first create the `.gitignore` git won't realize that you've deleted those files.

Also, ignore the fact that the line to the python gitignore has python in it, in order for git to recognize it the name must be exactly `.gitignore` it just happens to be that they maintain a lot of `.gitignore` files and they needed a way to make the corresponding language obvious

**Comment by RomeroPaola** [comment]
Please see the branch "removeVirtualenv" to verify this task.
